### ISSUE TITLE
Containerd configuration shim format problem

### ISSUE THREAD

**Issue by dierbei** [deislabs/containerd-wasm-shims#110]
I moved the built `containerd-shim-spin-v1` to `/usr/local/bin/`.

Then I try to modify the configuration file of containerd, the content is roughly as follows：
```toml
[metrics]
  address = ""
  grpc_histogram = false

[plugins.cri.containerd.runtimes.spin]
  runtime_type = "io.containerd.spin.v1"

[plugins]

  [plugins."io.containerd.gc.v1.scheduler"]
    deletion_threshold = 0
    mutation_threshold = 100
    pause_threshold = 0.02
    schedule_delay = "0s"
    startup_delay = "100ms"

  [plugins."io.containerd.grpc.v1.cri"]
```

But I encountered an error when I finally started containerd, the information is as follows：

```shell
# containerd
containerd: failed to load TOML from /etc/containerd/config.toml: invalid plugin key URI "cri" expect io.containerd.x.vx
```

how do i solve this problem？

**Comment by Mossaka** [comment]
Could you please try putting the section
```toml
[plugins.cri.containerd.runtimes.spin]
  runtime_type = "io.containerd.spin.v1"
```

under the `[plugins]` section?

**Comment by dierbei** [comment]
@Mossaka thanks for your advice. 

I will try it according to what you said.

**Comment by dierbei** [comment]
@Mossaka I still got the same error.

```shell
~/containerd-1.7.2# containerd
containerd: failed to load TOML from /etc/containerd/config.toml: invalid plugin key URI "cri" expect io.containerd.x.vx
```


Below is my configuration：
```toml

[metrics]
  address = ""
  grpc_histogram = false

[plugins]

  [plugins.cri.containerd.runtimes.spin]
    runtime_type = "io.containerd.spin.v1"

  [plugins."io.containerd.gc.v1.scheduler"]
    deletion_threshold = 0
    mutation_threshold = 100
    pause_threshold = 0.02
    schedule_delay = "0s"
    startup_delay = "100ms"
```

**Comment by dierbei** [comment]
But I found a solution：
```toml
    [plugins."io.containerd.grpc.v1.cri".containerd]
      default_runtime_name = "runc"
      disable_snapshot_annotations = true
      discard_unpacked_layers = false
      ignore_rdt_not_enabled_errors = false
      no_pivot = false
      snapshotter = "overlayfs"

      # The following is the configuration I added for spin 
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.spin]
         runtime_type = "io.containerd.spin.v1"
```

To my surprise, I successfully created the `Deployment`
